### ISSUE TITLE
Step 1 - Static *create* page

### ISSUE THREAD

**Issue by R-Rudolf** [NPeteCodes/BlogProject#1]
At url path "/create" with "save" button and String input for title and content.

**Comment by R-Rudolf** [comment]
Create the html file containing the button and the input fields, then save it.
For each request coming to /create anser the content of this given file.
How to read from file: [link](https://www.w3schools.com/nodejs/nodejs_filesystem.asp)

**Comment by NPeteCodes** [comment]
Index.html pushed with requested elements.

**Comment by R-Rudolf** [comment]
> Index.html pushed with requested elements.

Checked, looks cool :)
