### ISSUE TITLE
Step2 - Send data and save the into file

### ISSUE THREAD

**Issue by R-Rudolf** [NPeteCodes/BlogProject#2]
### Send data
Follow this guide: [link](https://www.w3schools.com/tags/att_form_method.asp)
Send data to "http://127.0.0.1:80/save".

### Receive data and save
Follow this comment: [link](https://stackoverflow.com/a/8640308)
When receiving POST data to the URL /save then parse the data in it with _querystring_.
Save into the directory "/posts" where the filename is the title+.txt and the content is in it.
How to write into a file, follow: [link](https://www.w3schools.com/nodejs/nodejs_filesystem.asp)

**Comment by R-Rudolf** [comment]
Send data works, will continue with saving

**Comment by NPeteCodes** [comment]
All done
