### ISSUE TITLE
Practice - FizzBuzz

### ISSUE THREAD

**Issue by R-Rudolf** [NPeteCodes/BlogProject#3]
Create a new nodejs file "fizzbuzz.js", which when executed writes out the numbers from 1 to 100.

However, if a number can be divided by 3 write "fizz" instead of the number.
If a number can be divided by 5, write "buzz" instead of the number.
When the number can be divided by both, write "fizzbuzz" instead.

See [Fizz buzz wiki](https://en.m.wikipedia.org/wiki/Fizz_buzz).

**Comment by NPeteCodes** [comment]
Check it out, its done!
