### ISSUE TITLE
Step 3 - MVP homepage

### ISSUE THREAD

**Issue by R-Rudolf** [NPeteCodes/BlogProject#5]
MVP: Minimum viable product

On the URL: "/" send the index.html static html file's content to the browser.

Homepage writes a welcome message and an example blogpost is shown with hardcoded title and content:
Title: "First weeks of the BlogProject journey"
Content:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

**Comment by NPeteCodes** [comment]
Task done in video session.
