### ISSUE TITLE
Step 4 - Dynamic homepage

### ISSUE THREAD

**Issue by R-Rudolf** [NPeteCodes/BlogProject#6]
Remove the original title and content from the index.html and replace them with the following expressions: "{{title}}", "{{content}}"

Create two variable in the function responding the home page:
title="foo", content="bar"

Enhance the home "/" request to load the index.html, and replace the "{{title}}" part to the value of the title variable. DO it for the content too.

**Comment by NPeteCodes** [comment]
Done in video session.
